# this is the template for scrcpy 1.9-ws & sndcpy
name: "{{ id }}"
# note: moustache has built-in anti-xss, so anything with a slash needs to have a & before it
services:
  redroid:
    image: "{{ &redroidImage }}"
    hostname: "{{ id }}-redroid"
#    ports:
#      - "5555:5555/tcp"
    privileged: true  # required for redroid
    restart: unless-stopped
    networks:
      '{{ externalNetworkName }}':
        driver_opts:
          com.docker.network.bandwidth.rx: "10M"  # 10 Mbps down
          com.docker.network.bandwidth.tx: "5M"  # 5 Mbps up
    volumes:
      - "{{ &baseDir }}/{{ redroidImageDataBasePath }}:/data-base"
      - type: volume
        source: redroid-diff
        target: /data-diff
    # https://github.com/remote-android/redroid-doc?tab=readme-ov-file#configuration
    command:
      - "androidboot.use_redroid_overlayfs=1"
      - "androidboot.use_memfd=true"
      - "androidboot.redroid_fps={{ redroidFps }}"
      - "androidboot.redroid_width={{ redroidWidth }}"
      - "androidboot.redroid_height={{ redroidHeight }}"
      - "androidboot.redroid_dpi={{ redroidDpi }}"
      - "androidboot.redroid_net_ndns=2"
      - "androidboot.redroid_net_dns1=1.1.1.1"
      - "androidboot.redroid_net_dns2=1.0.0.1"
      - "androidboot.redroid_net_proxy_type=pac" # static only works with http proxy, have to provide a pac file for socks5
      - "androidboot.redroid_net_proxy_pac=https://doppelgangerhq.com/api/devices/{{ id }}/proxy.pac"
      - "androidboot.redroid_gpu_mode=guest"  # doesn't work with auto/host on oracle
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 700M
    blkio_config:
      weight: 300  # always gives the orhcestrator priority to disk I/O
  scrcpy:
    # implementation note: this is a custom version of my scrcpy image that only runs sndcpy since scrcpy cannot accept a WS connection while it is already connected to
    image: "ghcr.io/regulad/workspaces-images:sndcpy"
    hostname: "{{ id }}-scrcpy"
    #    ports:
    #      - "6901:6901/tcp"
    #      - "4901:4901/tcp"
    shm_size: "512m"
    tty: true
    stdin_open: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 200M
    depends_on:
      - "redroid"
    # no network limits attached because arbitrary code cannot be run on this container
    networks:
      - "{{ externalNetworkName }}"
    environment:
      ADB_DEVICE: "{{ id }}-redroid:5555"
      SCRCPY_FPS: "{{ redroidFps }}"
      SCRCPY_WIDTH: "{{ redroidWidth }}"
      SCRCPY_HEIGHT: "{{ redroidHeight }}"
      # username: kasm_user
      VNC_PW: "password"
      # we never plan to connect to this, only use the pulseaudio for audio streaming which doesn't require a password
    blkio_config:
      weight: 400  # higher than the android, but lower than the orhcestrator

networks:
  '{{ externalNetworkName }}':
    external: true

volumes:
  redroid-diff:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "{{ &baseDir }}/{{ id }}-diff"
    name: "{{ id }}-redroid-diff"
    labels:
      com.docker.storage.quota.size: "17179869184"  # 16 GiB in bytes
