name: "{{ id }}"
# note: moustache has built-in anti-xss, so anything with a slash needs to have a & before it
services:
  redroid:
    image: "{{ &redroidImage }}"
    hostname: "{{ id }}-redroid"
#    ports:
#      - "5555:5555/tcp"
    privileged: true  # required for redroid
    restart: unless-stopped
    networks:
      - "{{{ externalNetworkName }}}"
    volumes:
      - "{{ &baseDir }}/{{ redroidImageDataBasePath }}:/data-base"
      - "{{ &baseDir }}/{{ id }}-diff:/data-diff"
    # https://github.com/remote-android/redroid-doc?tab=readme-ov-file#configuration
    command:
      - "androidboot.use_redroid_overlayfs=1"
      - "androidboot.use_memfd=true"
      - "androidboot.redroid_fps={{ redroidFps }}"
      - "androidboot.redroid_width={{ redroidWidth }}"
      - "androidboot.redroid_height={{ redroidHeight }}"
      - "androidboot.redroid_dpi={{ redroidDpi }}"
      - "androidboot.redroid_net_ndns=2"
      - "androidboot.redroid_net_dns1=1.1.1.1"
      - "androidboot.redroid_net_dns2=1.0.0.1"
#      TODO: proxy support
      - "androidboot.redroid_gpu_mode=guest"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 700M
networks:
  '{{ externalNetworkName }}':
    external: true
