/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/i59yRolZFM7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Inter } from 'next/font/google'

 inter({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import { Button } from "@/components/ui/button.tsx";
import Link from "next/link";
import { ReactNode } from "react";
import { RxPlus } from "react-icons/rx";

export function DeviceCardPage({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="flex items-center justify-between mb-8">
        <h2 className="text-2xl font-semibold">My Devices</h2>
        <Button asChild variant="outline" className="flex items-center gap-2">
          <Link href={"/devices/new"}>
            <RxPlus className="w-4 h-4" />
            Create New Device
          </Link>
        </Button>
      </div>
      <div className="flex flex-wrap -m-3">{children}</div>
    </div>
  );
}
