repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: "turbo"
        args: [ "type-check", "lint", "format" ]
        language: system
        pass_filenames: false
        files: \.(js|ts|tsx|json|yaml|yml|md|html|css|scss)$
