repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: "pnpm"
        args: ["format"]
        language: system
        pass_filenames: false
      - id: turbo
        name: turbo
        entry: "turbo"
        args: ["type-check", "lint", "test"]
        language: system
        pass_filenames: false
