repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: "pnpm"
        args: ["format"]
        language: system
        pass_filenames: false
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md|mdx|html|css|scss)$
      - id: turbo
        name: turbo
        entry: "turbo"
        args: ["type-check", "lint", "test"]
        language: system
        pass_filenames: false
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md|mdx|html|css|scss)$
