repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: "turbo"
        args: [ "type-check", "lint", "format", "test", "android:fetch" ]
        language: system
        pass_filenames: false
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md|mdx|html|css|scss)$
