name: "doppelganger"
services:
  web:
    image: "ghcr.io/nefum/doppelganger:web-latest"
    restart: unless-stopped
    hostname: "doppelganger"
    build:
      context: apps/web
      dockerfile: apps/web/Dockerfile
      args:
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
        - SENTRY_RELEASE=master
    ports:
      - "80:3000/tcp"
    volumes:
      # ANDROID_RUNTIME_DIR
      - "/mnt/doppelganger/prod:/mnt/doppelganger/prod"
      # DOCKER_HOST
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - ".env.local"
    networks:
      # EXTERNAL_NETWORK_NAME
      - "doppelganger"
  cron:
    image: "ghcr.io/regulad/http-docker-cron:latest"
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: "* * * * *"
      ENDPOINT: "http://doppelganger:3000/api/cron"
    networks:
      # EXTERNAL_NETWORK_NAME
      - "doppelganger"
networks:
  doppelganger:
    external: true
