name: "doppelganger"
services:
  app:
    image: "ghcr.io/regulad/doppelganger-front:latest"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000/tcp"
    volumes:
      # ANDROID_RUNTIME_DIR
      - "/mnt/doppelganger/prod:/mnt/doppelganger/prod"
      # DOCKER_HOST
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - ".env.local"
    networks:
      # EXTERNAL_NETWORK_NAME
      - "doppelganger"
networks:
  doppelganger:
    external: true
